import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import MyNav from "@/components/myNav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Tv 2 - bedst på breaking og live",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <MyNav/>
        {children}
      </body>
    </html>
  );
}
